<div class="wk_tidings_main">
<div class="wk_tidings_img">
<a href="[field:arcurl/]" target="_blank" title="[field:title/]"><img src="[field:litpic/]" alt="[field:title/]"/></a>	
</div>
<div class="wk_tidings_main_name">
<span class="wk_tidings_main_name2"><a href="[field:arcurl/]" target="_blank" title="[field:title/]">[field:title/]</a></span>
</div>
<div class="wk_tidings_main_cnt">
<span class="wk_tidings_main_cnt2">[field:infos/]...</span>
</div>
<div class="wk_tidings_main_more"><a target="_blank" title="more" href="[field:arcurl/]">more>></a> </div>
</div>