<li class="cl">
<h2><a href="[field:arcurl/]" target="_blank" class="xi2" title="[field:title/]"  style="">[field:title/]</a> </h2>
<p class="wk_bm_sm">[field:infos/]...</p>
<span class="xg1">
分类: <label><a href="[field:arcurl/]" class="xi2">[field:typename/]...</a></label>&nbsp;&nbsp;                            
<span class="xg1">时间: [field:pubdate function="MyDate('Y-m-d h:m',@me)"/]</span>
</span>
</li>