<div class="wk_case_list"> <a href="[field:arcurl/]" target="_blank" title="[field:title/]">
              <div class="wk_case_img"><img src="[field:litpic/]" width="275" height="190" alt="[field:title/]"/></div>
              <div class="wk_case_ico"></div>
              <div class="wk_case_xian"> <span class="wk_span_1"></span> <span class="wk_span_2"></span> <span class="wk_span_3"></span> <span class="wk_span_4"></span> </div>
              </a> </div>