<dl>
<dd style="background:url([field:litpic/]) no-repeat center center;background-size:cover"><a href="[field:arcurl/]" title="[field:title/]" target="_blank"></a></dd>
<dt><h3><a href="[field:arcurl/]" title="[field:title/]" target="_blank">[field:title/]</a></h3></dt>
<dt><a href="[field:arcurl/]" target="_blank" class="xi2">[field:typename/]</a><span class="pipe"></span>[field:pubdate function="MyDate('Y-m-d h:m',@me)"/]</dt>
<dt class="dt3">[field:infos/]...</dt>
</dl>