<?php
$z[0]=Array("field","",219,238);
$z[0][4]['name']="title";
$z[1]=Array("global","",239,265);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1123,1162);
$z[2][4]['filename']="header_m.htm";
$z[3]=Array("field","",1459,1488);
$z[3][4]['name']="typename";
$z[4]=Array("global","",1831,1856);
$z[4][4]['name']="cfg_cmsurl";
$z[5]=Array("channel","\r\n        <li><a href=\"list.php?tid=[field:id/]\" title=\"[field:typename/]\">[field:typename/]</a> <span class=\"commonfont class-down\">&#xe60c;</span></li>\r\n        ",2267,2586);
$z[5][4]['type']="son";
$z[5][4]['row']="10";
$z[5][4]['currentstyle']="<li><a href='list.php?tid=~id~' ~rel~><span>~typename~</span></a> </li>";
$z[6]=Array("field","",2736,2755);
$z[6][4]['name']="title";
$z[7]=Array("field","",2804,2822);
$z[7][4]['name']="body";
$z[8]=Array("prenext","",2846,2874);
$z[8][4]['get']="prewap";
$z[9]=Array("prenext","",2876,2905);
$z[9][4]['get']="nextwap";
$z[10]=Array("type"," <a href=\"list.php?tid=[field:id/]\" title=\"返回列表\" class=\"back\">返回列表</a>",2909,3018);
$z[11]=Array("include","",3069,3108);
$z[11][4]['filename']="footer_m.htm";

?>