<li >
              <dl>
                <dt>[field:pubdate function="MyDate('Y-m-d',@me)"/]</dt>
              </dl>
              <h4><a href="[field:arcurl/]" title="[field:title/]" target="_blank">[field:title/]</a></h4>
              <div class="wk_news_des">[field:infos/]...</div>
              <div class="wk_news_more"><a href="[field:arcurl/]" title="阅读更多" target="_blank"></a></div>
            </li>