<?php
$z[0]=Array("global","",128,154);
$z[0][4]['name']="cfg_powerby";
$z[1]=Array("global","",231,255);
$z[1][4]['name']="cfg_beian";
$z[2]=Array("global","",257,281);
$z[2][4]['name']="cfg_beian";
$z[3]=Array("flink","[field:link /]",317,380);
$z[3][4]['type']="textall";
$z[3][4]['row']="20";
$z[4]=Array("global","",917,939);
$z[4][4]['name']="cfg_qqa";
$z[5]=Array("global","",1271,1298);
$z[5][4]['name']="cfg_shouqian";
$z[6]=Array("global","",1366,1392);
$z[6][4]['name']="cfg_shouhou";

?>