<?php
$z[0]=Array("global","",380,406);
$z[0][4]['name']="cfg_company";
$z[1]=Array("global","",446,472);
$z[1][4]['name']="cfg_company";
$z[2]=Array("type","<a href=\"[field:typeurl/]\" hidefocus=\"true\"  >[field:typename/]</a>",794,895);
$z[2][4]['typeid']="1";
$z[3]=Array("type","<a href=\"[field:typeurl/]\" hidefocus=\"true\"  >[field:typename/]</a>",1005,1106);
$z[3][4]['typeid']="5";
$z[4]=Array("type","<a href=\"[field:typeurl/]\" hidefocus=\"true\"  >[field:typename/]</a>",1216,1318);
$z[4][4]['typeid']="10";
$z[5]=Array("type","<a href=\"[field:typeurl/]\" hidefocus=\"true\"  >[field:typename/]</a>",1428,1530);
$z[5][4]['typeid']="13";
$z[6]=Array("type","<a href=\"[field:typeurl/]\" hidefocus=\"true\"  >[field:typename/]</a>",1640,1742);
$z[6][4]['typeid']="15";
$z[7]=Array("channel","\r\n    <li><a href=\"[field:typelink/]\" hidefocus=\"true\" >[field:typename/]</a></li>\r\n    ",1919,2060);
$z[7][4]['typeid']="1";
$z[7][4]['noself']="yes";
$z[8]=Array("channel","\r\n    <li><a href=\"[field:typelink/]\" hidefocus=\"true\" >[field:typename/]</a></li>\r\n    ",2141,2282);
$z[8][4]['typeid']="5";
$z[8][4]['noself']="yes";
$z[9]=Array("channel","\r\n    <li><a href=\"[field:typelink/]\" hidefocus=\"true\" >[field:typename/]</a></li>\r\n    ",2363,2505);
$z[9][4]['typeid']="10";
$z[9][4]['noself']="yes";
$z[10]=Array("channel","\r\n    <li><a href=\"[field:typelink/]\" hidefocus=\"true\" >[field:typename/]</a></li>\r\n    ",2664,2806);
$z[10][4]['typeid']="13";
$z[10][4]['noself']="yes";
$z[11]=Array("channel","\r\n    <li><a href=\"[field:typelink/]\" hidefocus=\"true\" >[field:typename/]</a></li>\r\n    ",2887,3029);
$z[11][4]['typeid']="15";
$z[11][4]['noself']="yes";

?>