<?php
$z[0]=Array("field","",219,238);
$z[0][4]['name']="title";
$z[1]=Array("global","",239,265);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1123,1162);
$z[2][4]['filename']="header_m.htm";
$z[3]=Array("field","",1459,1488);
$z[3][4]['name']="typename";
$z[4]=Array("global","",1831,1856);
$z[4][4]['name']="cfg_cmsurl";
$z[5]=Array("channel","\r\n        <li><a href=\"list.php?tid=[field:id/]\" title=\"[field:typename/]\">[field:typename/]</a> <span class=\"commonfont class-down\">&#xe60c;</span></li>\r\n        ",2267,2577);
$z[5][4]['type']="son";
$z[5][4]['currentstyle']="<li><a href='list.php?tid=~id~' ~rel~><span>~typename~</span></a> </li>";
$z[6]=Array("field","",2746,2767);
$z[6][4]['name']="content";
$z[7]=Array("include","",2821,2860);
$z[7][4]['filename']="footer_m.htm";

?>