<?php
$z[0]=Array("field","",253,272);
$z[0][4]['name']="title";
$z[1]=Array("global","",273,299);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",339,368);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",407,465);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1135,1170);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel","\n<li><a href=\"[field:typeurl/]\" title=\"[field:typename/]\" >[field:typename/]</a></li>\n",1385,1608);
$z[5][4]['type']="son";
$z[5][4]['row']="8";
$z[5][4]['currentstyle']="<li><a href='~typelink~' title='~typename~' class='a'>~typename~</a></li>";
$z[6]=Array("list","\n<dl>\n<dd style=\"background:url([field:litpic/]) no-repeat center center;background-size:cover\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\" target=\"_blank\"></a></dd>\n<dt><h3><a href=\"[field:arcurl/]\" title=\"[field:title/]\" target=\"_blank\">[field:title/]</a></h3></dt>\n<dt><a href=\"[field:arcurl/]\" target=\"_blank\" class=\"xi2\">[field:typename/]</a><span class=\"pipe\"></span>[field:pubdate function=\"MyDate('Y-m-d h:m',@me)\"/]</dt>\n<dt class=\"dt3\">[field:infos/]...</dt>\n</dl>\n",1950,2481);
$z[6][4]['pagesize']="15";
$z[6][4]['titlelen']="80";
$z[7]=Array("pagelist","",2630,2701);
$z[7][4]['listitem']="info,index,end,pre,next,pageno";
$z[7][4]['listsize']="5";
$z[8]=Array("include","",3639,3676);
$z[8][4]['filename']="footer.htm";

?>