<?php
$z[0]=Array("field","",257,276);
$z[0][4]['name']="title";
$z[1]=Array("global","",277,303);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",344,373);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",413,471);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1164,1199);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel","\r\n<li><a href=\"[field:typeurl/]\" title=\"[field:typename/]\" >[field:typename/]</a></li>\r\n",2146,2371);
$z[5][4]['type']="son";
$z[5][4]['row']="8";
$z[5][4]['currentstyle']="<li><a href='~typelink~' title='~typename~' class='a'>~typename~</a></li>";
$z[6]=Array("include","",6565,6602);
$z[6][4]['filename']="footer.htm";

?>