<?php
$z[0]=Array("field","",253,272);
$z[0][4]['name']="title";
$z[1]=Array("global","",273,299);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",339,368);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",407,465);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1144,1179);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel","\n<li><a href=\"[field:typeurl/]\" title=\"[field:typename/]\" >[field:typename/]</a></li>\n",1762,1985);
$z[5][4]['type']="son";
$z[5][4]['row']="8";
$z[5][4]['currentstyle']="<li><a href='~typelink~' title='~typename~' class='a'>~typename~</a></li>";
$z[6]=Array("global","",5439,5463);
$z[6][4]['name']="cfg_email";
$z[7]=Array("global","",5465,5489);
$z[7][4]['name']="cfg_email";
$z[8]=Array("include","",7653,7690);
$z[8][4]['filename']="footer.htm";

?>