<?php
$z[0]=Array("field","",219,238);
$z[0][4]['name']="title";
$z[1]=Array("global","",239,265);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1123,1162);
$z[2][4]['filename']="header_m.htm";
$z[3]=Array("field","",1459,1488);
$z[3][4]['name']="typename";
$z[4]=Array("global","",1831,1856);
$z[4][4]['name']="cfg_cmsurl";
$z[5]=Array("channel","\r\n        <li><a href=\"list.php?tid=[field:id/]\" title=\"[field:typename/]\">[field:typename/]</a> <span class=\"commonfont class-down\">&#xe60c;</span></li>\r\n        ",2267,2586);
$z[5][4]['type']="son";
$z[5][4]['row']="10";
$z[5][4]['currentstyle']="<li><a href='list.php?tid=~id~' ~rel~><span>~typename~</span></a> </li>";
$z[6]=Array("list","\r\n      <li class=\"loop news2\"><a href=\"view.php?aid=[field:id/]\" title=\"[field:title/]\"><span>[field:title/]</span><span>[field:pubdate function=\"MyDate('Y/m/d',@me)\"/]</span></a></li>\r\n      ",2764,2994);
$z[6][4]['pagesize']="6";
$z[7]=Array("pagelist","",3030,3096);
$z[7][4]['listitem']="index,end,pre,next,pageno";
$z[7][4]['listsize']="1";
$z[8]=Array("include","",3147,3186);
$z[8][4]['filename']="footer_m.htm";

?>